platform:
  - x86

environment:
  CYG_ROOT: "C:\\cygwin"
  CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
  CYGWIN: "winsymlinks:native"
  CUSTOM_OPAM: "1"
  OPAM_COMP: "4.03.0+mingw64c"

install:
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P diffutils.3.5-1 -P make -P git -P perl -P mingw64-x86_64-gcc-core"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/scripts/appveyor.sh'"

artifacts:
  - path: "vpnkit.exe"
  - path: "OSS-LICENSES"
  - path: "COMMIT"
