[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[override]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "master"

[[constraint]]
  name = "github.com/linuxkit/virtsock"
  source = "github.com/djs55/virtsock"
  revision = "4813e31717edd6d27179715ce5c919091f349892"

[[constraint]]
  name = "github.com/docker/go-p9p"
  revision = "87ae8514a3a2d9684994a6c319f96ba9e18a062e"

[[constraint]]
  name = "github.com/moby/datakit"
  version = "0.12.2"

[[constraint]]
  name = "github.com/google/uuid"
  revision = "7e072fc3a7be179aee6d3359e46015aa8c995314"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "059132a15dd08d6704c67711dae0cf35ab991756"
